# Generated by Django 5.2.7 on 2025-12-12 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorvolunteer',
            name='business_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='donorvolunteer',
            name='business_nature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_nature_lookup', to='heart_charity.lookup'),
        ),
        migrations.AddField(
            model_name='donorvolunteer',
            name='business_salutation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='donorvolunteer',
            name='nature_of_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nature_of_service_lookup', to='heart_charity.lookup'),
        ),
        migrations.AddField(
            model_name='donorvolunteer',
            name='org_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='donorvolunteer',
            name='org_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_type_lookup', to='heart_charity.lookup'),
        ),
    ]
