# Generated by Django 5.2.7 on 2026-03-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationowner',
            name='box_owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donationowner',
            name='box_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='donorvolunteer',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
