# Generated by Django 5.2.7 on 2025-12-12 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0002_donorvolunteer_business_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donationpaymentbox',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donationpaymentbox',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationpaymentbox',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_donation_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
