# Generated by Django 5.2.7 on 2026-03-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0002_donationowner_box_owner_donationowner_box_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationowner',
            name='box_owner',
        ),
        migrations.RemoveField(
            model_name='donationowner',
            name='box_percentage',
        ),
        migrations.AddField(
            model_name='donationbox',
            name='box_owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donationbox',
            name='box_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
