# Generated by Django 5.2.7 on 2026-06-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0003_remove_donationowner_box_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorvolunteer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
