# Generated by Django 5.2.7 on 2025-11-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heart_charity", "0003_userrole"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donation",
            name="donor",
        ),
        migrations.AddField(
            model_name="donation",
            name="donors",
            field=models.ManyToManyField(
                limit_choices_to={"person_type": "Donor"},
                related_name="donations",
                to="heart_charity.donorvolunteer",
            ),
        ),
    ]
