# Generated by Django 5.2.7 on 2026-06-15 05:02

from django.db import migrations, models

def combine_addresses(apps, schema_editor):
    DonorVolunteer = apps.get_model('heart_charity', 'DonorVolunteer')
    for donor in DonorVolunteer.objects.all():
        parts = []
        if donor.house_number:
            parts.append(donor.house_number.strip())
        if donor.building_name:
            parts.append(donor.building_name.strip())
        if donor.street_name:
            parts.append(donor.street_name.strip())
        if donor.landmark:
            parts.append(donor.landmark.strip())
        if donor.area:
            parts.append(donor.area.strip())
        
        combined = ", ".join([p for p in parts if p])
        donor.address = combined if combined else "N/A"
        donor.save()

def split_addresses(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0004_alter_donorvolunteer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorvolunteer',
            name='address',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
        migrations.RunPython(combine_addresses, reverse_code=split_addresses),
        migrations.RemoveField(
            model_name='donorvolunteer',
            name='area',
        ),
        migrations.RemoveField(
            model_name='donorvolunteer',
            name='building_name',
        ),
        migrations.RemoveField(
            model_name='donorvolunteer',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='donorvolunteer',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='donorvolunteer',
            name='street_name',
        ),
    ]
