# Generated by Django 5.2.7 on 2025-12-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0004_donation_deleted_by_donation_hist_deleted_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='donationpaymentbox',
            name='receipt_id',
            field=models.CharField(max_length=20, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='receipt_id',
            field=models.CharField(max_length=20, blank=True, null=True),
        ),
    ]
