# Generated by Django 5.2.7 on 2025-12-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0005_receiptsequence_donationpaymentbox_receipt_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='receipt_id',
            field=models.CharField( max_length=20,
        unique=True,
        blank=True,
        null=True),
        ),
        migrations.AlterField(
            model_name='donationpaymentbox',
            name='receipt_id',
            field=models.CharField( max_length=20,
        unique=True,
        blank=True,
        null=True),
        ),
    ]
