# Generated by Django 5.2.7 on 2025-11-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heart_charity", "0005_donorvolunteer_age_donorvolunteer_area_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donorvolunteer",
            name="id_number",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
