# Generated by Django 5.2.7 on 2026-06-19 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0005_remove_donorvolunteer_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorvolunteer',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donorvolunteer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donorvolunteer',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donorvolunteer',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='donorvolunteer',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donorvolunteer',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donorvolunteer',
            name='id_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_type_lookup', to='heart_charity.lookup'),
        ),
        migrations.AlterField(
            model_name='donorvolunteer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donorvolunteer',
            name='old_box_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donorvolunteer',
            name='person_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_type_lookup', to='heart_charity.lookup'),
        ),
        migrations.AlterField(
            model_name='donorvolunteer',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='donorvolunteer',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
