# Generated by Django 5.2.7 on 2026-06-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0006_donorvolunteer_area_alter_donorvolunteer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorvolunteer',
            name='old_box_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
