# Generated by Django 5.2.7 on 2025-11-19 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heart_charity", "0006_alter_donorvolunteer_id_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donorvolunteer",
            name="id_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="id_type_lookup",
                to="heart_charity.lookup",
            ),
        ),
    ]
