# Generated by Django 5.2.7 on 2025-11-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heart_charity", "0007_alter_donorvolunteer_id_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donorvolunteer",
            name="id_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
