# Generated by Django 5.2.7 on 2026-07-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0007_alter_donorvolunteer_old_box_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorvolunteer',
            name='contact_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='donorvolunteer',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donorvolunteer',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='donorvolunteer',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donorvolunteer',
            name='pan_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
