# Generated by Django 5.2.7 on 2025-12-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0007_alter_donation_receipt_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='receipt_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='donationpaymentbox',
            name='receipt_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
