# Generated by Django 5.2.7 on 2025-12-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0008_alter_donation_receipt_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='donation',
            name='name_of_bank',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='donationpaymentbox',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='donationpaymentbox',
            name='name_of_bank',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='donationpaymentbox',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction ID'),
        ),
    ]
