# Generated by Django 5.2.7 on 2026-09-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0009_alter_donation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationpaymentbox',
            name='donor_type',
            field=models.CharField(choices=[('Donor', 'Donor'), ('Danpeti Owner', 'Danpeti Owner')], default='Danpeti Owner', max_length=20, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='donationpaymentbox',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='donationpaymentbox',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='donationpaymentbox',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle Name'),
        ),
        migrations.AddField(
            model_name='donationpaymentbox',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AddField(
            model_name='donationpaymentbox',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='PAN Number'),
        ),
        migrations.AddField(
            model_name='donationpaymentbox',
            name='want_80g',
            field=models.BooleanField(default=False, verbose_name='80G Benefit'),
        ),
        migrations.AddField(
            model_name='donationpaymentbox_hist',
            name='donor_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='donationpaymentbox_hist',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donationpaymentbox_hist',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donationpaymentbox_hist',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donationpaymentbox_hist',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='donationpaymentbox_hist',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='donationpaymentbox_hist',
            name='want_80g',
            field=models.BooleanField(default=False),
        ),
    ]
