# Generated by Django 5.2.7 on 2025-11-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heart_charity", "0009_alter_donorvolunteer_person_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="donors",
            field=models.ManyToManyField(
                limit_choices_to={"person_type__lookup_name": "Donor"},
                related_name="donations",
                to="heart_charity.donorvolunteer",
            ),
        ),
    ]
