# Generated by Django 5.2.7 on 2025-12-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0009_donation_branch_donation_name_of_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
