# Generated by Django 5.2.7 on 2026-09-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0010_donationpaymentbox_donor_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorvolunteer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
