# Generated by Django 5.2.7 on 2025-11-25 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heart_charity", "0010_alter_donation_donors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donation",
            name="donation_amount",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="donation_date",
        ),
        migrations.AlterField(
            model_name="donation",
            name="donation_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="donation_categories",
                to="heart_charity.lookup",
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="donation_mode",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="donation_modes",
                to="heart_charity.lookup",
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="payment_method",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_methods",
                to="heart_charity.lookup",
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="payment_status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_statuses",
                to="heart_charity.lookup",
            ),
        ),
    ]
