# Generated by Django 5.2.7 on 2026-01-07 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0010_donation_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationpaymentbox',
            name='receipt_id',
        ),
        migrations.AlterField(
            model_name='donationpaymentbox',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='donationpaymentbox',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_payments', to='heart_charity.donorvolunteer'),
        ),
    ]
