# Generated by Django 5.2.7 on 2026-01-07 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0011_remove_donationpaymentbox_receipt_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationpaymentbox_hist',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_payment_history', to='heart_charity.donorvolunteer'),
        ),
    ]
