# Generated by Django 5.2.7 on 2026-09-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0011_alter_donorvolunteer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationpaymentbox',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AddField(
            model_name='donationpaymentbox',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Razorpay Order ID'),
        ),
        migrations.AddField(
            model_name='donationpaymentbox_hist',
            name='payment_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='donationpaymentbox_hist',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donationpaymentbox_hist',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
