# Generated by Django 5.2.7 on 2026-01-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0012_alter_donationpaymentbox_hist_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationpaymentbox',
            name='receipt_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='donationpaymentbox',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
