# Generated by Django 5.2.7 on 2026-09-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0013_ownerdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationbox',
            name='old_box_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
