# Generated by Django 5.2.7 on 2026-01-28 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0013_donationpaymentbox_receipt_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationbox',
            name='location',
        ),
    ]
