# Generated by Django 5.2.7 on 2026-03-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0014_remove_donationbox_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationpaymentbox',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='donationpaymentbox',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], default='cash', max_length=10),
        ),
    ]
