# Generated by Django 5.2.7 on 2026-03-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0015_remove_donationpaymentbox_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationpaymentbox_hist',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='donationpaymentbox_hist',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], default='cash', max_length=10),
        ),
    ]
