# Generated by Django 5.2.7 on 2026-09-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0015_donationbox_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerdetail',
            name='zone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donationbox',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Maintainance', 'Maintainance'), ('Inactive', 'Inactive'), ('return', 'Return')], db_index=True, default='Active', max_length=20),
        ),
    ]
