# Generated by Django 5.2.7 on 2026-03-09 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0016_remove_donationpaymentbox_hist_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationpaymentbox',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='donationpaymentbox',
            name='name_of_bank',
        ),
        migrations.RemoveField(
            model_name='donationpaymentbox',
            name='transaction_id',
        ),
    ]
