# Generated by Django 5.2.7 on 2026-09-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0017_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pan_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='emp_pan_cards/'),
        ),
    ]
