# Generated by Django 5.2.7 on 2026-03-12 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0017_remove_donationpaymentbox_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationpaymentbox',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='donationpaymentbox',
            name='name_of_bank',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='donationpaymentbox',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction ID'),
        ),
        migrations.AlterField(
            model_name='donationpaymentbox',
            name='payment_mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_modes_box', to='heart_charity.lookup'),
        ),
    ]
