# Generated by Django 5.2.7 on 2026-03-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0018_donationpaymentbox_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationpaymentbox_hist',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
